export class PlanScreen {
  constructor(app) { this.app = app; this.host = null; this.activeId = ''; this._bound = false; }
  mount(host) { if (!host || this.host === host) return; this.host = host; this._bind(); this.render(); }
  show() { this.render(); }
  _store() { return this.app.storage.seasonStore; }
  _persist() { this._store().persist(); this.render(); }
  _active() { const plans = this._store().plans(); return this._store().getPlan(this.activeId) || plans[0] || null; }
  ensurePlan() { let plan = this._active(); if (!plan) { plan = this._store().createPlan('Game Plan'); this.activeId = plan.id; this._store().persist(); } return plan; }
  addFinding(item) { const plan = this.ensurePlan(); this._store().addPlanItem(plan.id, item); this._store().persist(); this.render(); return plan; }
  render() {
    if (!this.host) return; const plans = this._store().plans(); const plan = this._active(); if (plan) this.activeId = plan.id;
    this.host.innerHTML = `<div class="ws-plan-head"><div><div class="ws-eyebrow">Turn findings into action</div><h1>GAME PLAN</h1><p>Build a staff-ready plan from Study results and linked film.</p></div><button class="ws-btn ws-primary" data-plan-action="create">New plan</button></div>
      ${plan ? `<div class="ws-plan-toolbar"><label>Plan<select id="wsPlanSelect">${plans.map(p=>`<option value="${this._esc(p.id)}"${p.id===plan.id?' selected':''}>${this._esc(p.name)}</option>`).join('')}</select></label><label class="grow">Name<input id="wsPlanName" value="${this._esc(plan.name)}"></label><button class="ws-btn" data-plan-action="watch" ${this.app.studyPlan.planRefs(plan).length?'':'disabled'}>Watch plan · ${this.app.studyPlan.planRefs(plan).length}</button><button class="ws-btn danger" data-plan-action="delete">Delete</button></div><div class="ws-plan-grid"><section><h2>PLAN ITEMS <span>${plan.items.length}</span></h2><div class="ws-plan-items">${plan.items.length?plan.items.map(item=>`<article><div><span>${this._esc(item.kind)}</span><strong>${this._esc(item.label||'Untitled item')}</strong><small>${item.refs.length} linked play${item.refs.length===1?'':'s'}</small></div><button class="ws-btn ws-small" data-plan-watch="${this._esc(item.id)}" ${item.refs.length?'':'disabled'}>Watch</button><button class="ws-icon-btn" data-plan-remove="${this._esc(item.id)}" aria-label="Remove ${this._esc(item.label||'item')}">×</button></article>`).join(''):'<div class="ws-plan-empty">Save a finding from Study to begin this plan.</div>'}</div></section><section><h2>STAFF NOTES</h2><textarea id="wsPlanNotes" placeholder="Install notes, assignments, and meeting emphasis">${this._esc(plan.notes)}</textarea></section></div>`:'<div class="ws-plan-empty large"><strong>No game plan yet</strong><span>Create a plan, then save findings from Study.</span><button class="ws-btn ws-primary" data-plan-action="create">Create game plan</button></div>'}`;
  }
  _bind() { if (this._bound) return; this._bound=true; this.host.addEventListener('change',e=>{if(e.target.id==='wsPlanSelect'){this.activeId=e.target.value;this.render();}if(e.target.id==='wsPlanName'){this._store().renamePlan(this.activeId,e.target.value);this._persist();}if(e.target.id==='wsPlanNotes'){this._store().setPlanNotes(this.activeId,e.target.value);this._persist();}}); this.host.addEventListener('click',async e=>{const action=e.target.closest('[data-plan-action]')?.dataset.planAction;if(action==='create'){const p=this._store().createPlan(`Game Plan ${this._store().plans().length+1}`);this.activeId=p.id;this._persist();}if(action==='delete'&&this._active()){const plan=this._active();const ok=await this.app.tagger._confirmDialog(`Delete "${plan.name}" and its ${plan.items.length} saved item${plan.items.length===1?'':'s'}?`, 'Delete Plan');if(ok){this._store().deletePlan(plan.id);this.activeId='';this._persist();}}if(action==='watch'&&this._active())this.app.studyScreen._watch(this.app.studyPlan.planRefs(this._active()),this._active().name);const remove=e.target.closest('[data-plan-remove]')?.dataset.planRemove;if(remove){this._store().removePlanItem(this.activeId,remove);this._persist();}const watch=e.target.closest('[data-plan-watch]')?.dataset.planWatch;if(watch){const item=this._active()?.items.find(i=>i.id===watch);if(item)this.app.studyScreen._watch(item.refs,item.label);}}); }
  _esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
}
