/* Design-only state. No application imports, browser storage, or persistence writes. */
const icon = name => `<svg aria-hidden="true"><use href="../../assets/icons.svg#icon-${name}"></use></svg>`;
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const seasonTitle = season => `${season.year} \u00b7 ${season.level}${season.label ? ` \u00b7 ${season.label}` : ''}`;
const shortDate = date => date ? new Date(`${date}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'}) : 'Date not set';
const fixtureGames = [
  {id:'g1',opponent:'St. Peter Lutheran Patriots',opponentSchool:'St. Peter Lutheran',opponentNickname:'Patriots',date:'2025-09-07',week:1,plays:67,charted:67,score:[41,0],clips:69,photo:'st-peter',phase:[29,20,18],duration:'24:16'},
  {id:'g2',opponent:'ND Prep Fighting Irish',opponentSchool:'ND Prep',opponentNickname:'Fighting Irish',date:'2025-09-07',week:2,plays:74,charted:74,score:[0,13],clips:79,photo:null,phase:[30,28,16],duration:'28:04'},
  {id:'g3',opponent:'OL Refuge Ravens',opponentSchool:'OL Refuge',opponentNickname:'Ravens',date:'2025-09-13',week:3,plays:78,charted:78,score:[7,13],clips:81,photo:'refuge',phase:[32,29,17],duration:'26:40'},
  {id:'g4',opponent:'OL Sorrows Lancers',opponentSchool:'OL Sorrows',opponentNickname:'Lancers',date:'2025-09-20',week:4,plays:67,charted:67,score:[18,6],clips:67,photo:'sorrows',phase:[28,25,14],duration:'23:08'},
  {id:'g5',opponent:'OL Lakes Lakers',opponentSchool:'OL Lakes',opponentNickname:'Lakers',date:'2025-09-27',week:5,plays:82,charted:82,score:[13,13],clips:89,photo:'lakes',phase:[34,30,18],duration:'30:12'},
  {id:'g6',opponent:'Holy Family Wildcats',opponentSchool:'Holy Family',opponentNickname:'Wildcats',date:'2025-10-11',week:6,plays:72,charted:72,score:[27,0],clips:81,photo:'holy-family',phase:[33,26,13],duration:'27:32'}
].map(game=>({...game,film:true}));
const baseSeasons = [
  {id:'jv25',programId:'mavericks',year:'2025',level:'JV',kind:'program',roster:32,record:'3-2-1',games:fixtureGames},
  {id:'varsity26',programId:'mavericks',year:'2026',level:'Varsity',kind:'program',roster:44,record:'0-0',games:[{...fixtureGames[0],id:'v1',date:'2026-09-05',plays:0,charted:0,score:null,clips:0,film:false,photo:null}]},
  {id:'jv26',programId:'mavericks',year:'2026',level:'JV',kind:'program',roster:28,record:'0-0',games:[{...fixtureGames[1],id:'a1',date:'2026-08-29',week:1,plays:50,charted:32,score:null,photo:null,lastPlay:33,phase:[22,18,10]},{...fixtureGames[2],id:'a2',date:'2026-09-05',week:2,plays:0,charted:0,clips:0,score:null,photo:null,film:false}]},
  {id:'scout26',programId:'mavericks',year:'2026',level:'JV',kind:'scout',opponent:'Notre Dame Prep',games:[{id:'s1',opponent:'Notre Dame Prep',teamA:'Notre Dame Prep',teamB:'Bishop Foley',date:'2026-08-28',week:null,plays:64,charted:41,clips:68,score:[21,14],photo:null,film:true,phase:[29,23,12],duration:'28:16',lastPlay:42},{id:'s2',opponent:'Notre Dame Prep',teamA:'Notre Dame Prep',teamB:'Divine Child',date:'2026-08-21',week:null,plays:58,charted:58,clips:62,score:[14,7],photo:null,film:true,phase:[26,20,12],duration:'25:10'}]}
];
const initial = new URLSearchParams(location.search).get('state') || 'season';
const state = {programs:[{id:'mavericks',name:'St. Joseph Mavericks',school:'St. Joseph',nickname:'Mavericks'}],programId:'mavericks',seasons:structuredClone(baseSeasons),mode:'program',page:'season',seasonId:'jv25',gameId:'g6',view:'grid',filter:'all',query:'',sort:'newest',firstMode:'program'};
const $ = selector => document.querySelector(selector);
const currentProgram = () => state.programs.find(program=>program.id===state.programId);
const currentSeason = () => state.seasons.find(season=>season.id===state.seasonId && season.programId===state.programId && season.kind===state.mode);
const currentGame = () => currentSeason()?.games.find(game=>game.id===state.gameId);
const fullIdentity = (school,nickname='') => [school.trim(),nickname.trim()].filter(Boolean).join(' ');
function gameIdentities(game){
  return state.mode==='scout'
    ? [{name:game.teamA,nickname:game.teamANickname},{name:game.teamB,nickname:game.teamBNickname}]
    : [currentProgram(),{name:game.opponent,nickname:game.opponentNickname}];
}
function matchupNames(game){
  const teams=gameIdentities(game),names=teams.map(team=>team.nickname||team.name);
  return names[0].toLowerCase()===names[1].toLowerCase()?teams.map(team=>team.name):names;
}
const gameTitle = game => matchupNames(game).join(' vs. ');
const fullGameTitle = game => gameIdentities(game).map(team=>team.name).join(' vs. ');
function identityFields(key,label,school='',nickname=''){
  return `<div class="identity-fields"><label class="form-field">${label}: school / organization<input name="${key}" value="${esc(school)}" required placeholder="e.g. St. Joseph"></label><label class="form-field"><span>Nickname <small>Optional</small></span><input name="${key}Nickname" value="${esc(nickname)}" placeholder="e.g. Mavericks"></label></div>`;
}
const levelRank = {Varsity:0,JV:1,Freshman:2};
function sortedSeasons(){return state.seasons.filter(season=>season.programId===state.programId && season.kind===state.mode).sort((a,b)=>Number(b.year)-Number(a.year)||(levelRank[a.level]??3)-(levelRank[b.level]??3)||(a.opponent||'').localeCompare(b.opponent||''));}
function setPreview(value){
  clearTimeout(announce.timer);$('#announcement').textContent='';
  state.seasons=structuredClone(baseSeasons);state.programs=[{id:'mavericks',name:'St. Joseph Mavericks',school:'St. Joseph',nickname:'Mavericks'}];state.programId='mavericks';
  Object.assign(state,{mode:'program',page:'season',seasonId:'jv25',gameId:'g6',query:'',filter:'all'});
  if(value==='first'){state.seasons=[];state.programs=[];state.programId=null;state.seasonId=null;state.gameId=null;state.page='first';state.firstMode='program';}
  if(value==='library'){state.page='library';state.seasonId=null;state.gameId=null;}
  if(value==='scout'){state.mode='scout';state.seasonId='scout26';state.gameId='s1';}
  if(value==='progress'){state.seasonId='jv26';state.gameId='a1';}
  $('#preview-state').value=value;render();
}
function announce(text){$('#announcement').textContent=text;clearTimeout(announce.timer);announce.timer=setTimeout(()=>$('#announcement').textContent='',3500);}
function command(action,label,style='',symbol='',attrs=''){return `<button type="button" class="command ${style}" data-action="${action}" ${attrs}>${symbol?icon(symbol):''}${label}</button>`;}
function railLink(action,label,symbol='',active=false,detail='',attrs='',year=''){return `<button class="rail-link ${active?'active':''}" data-action="${action}" ${attrs}${active?' aria-current="page"':''}>${symbol?icon(symbol):''}<span class="text"><strong>${year?`<span class="mobile-year">${esc(year)} &middot; </span>`:''}${esc(label)}</strong>${detail?`<small>${esc(detail)}</small>`:''}</span></button>`;}
function render(){
  document.body.dataset.mode=state.mode;document.body.dataset.page=state.page;
  $('#main-nav').innerHTML=[['home','Home',''],['breakdown','Break Down','play'],['study','Study','film'],['reports','Reports','stats'],['plan','Plan','notes']].map(([route,label,symbol])=>`<button class="${route==='home'?'active':''}" data-route="${route}" ${route==='home'?'aria-current="page"':''}>${symbol?icon(symbol):''}${label}</button>`).join('');
  document.querySelectorAll('[data-mode]').forEach(button=>{const active=button.dataset.mode===state.mode;button.classList.toggle('active',active);button.setAttribute('aria-pressed',active);});
  $('#program').innerHTML=state.programs.map(program=>`<option value="${esc(program.id)}">${esc(program.name)}</option>`).join('')+`<option value="new">${state.programs.length?'Add program...':'Create program'}</option>`;
  $('#program').value=state.programId||'new';
  renderRail();renderMain();
}
function renderRail(){
  const season=currentSeason(),seasons=sortedSeasons();let year='';
  const rows=seasons.map(item=>{const heading=year!==item.year?`<h3 class="rail-year">${esc(item.year)}</h3>`:'';year=item.year;return heading+railLink('season',item.kind==='scout'?item.opponent:item.level,'folder',state.page==='season'&&item.id===state.seasonId,`${item.games.length} ${item.kind==='scout'?'source games':item.games.length===1?'game':'games'}`,`data-id="${item.id}" aria-label="${esc(currentProgram().name)} ${esc(item.year)} ${esc(item.kind==='scout'?item.opponent+' '+item.level:item.level)}"`,item.year);}).join('');
  $('#season-rail').innerHTML=`<div><div class="rail-heading"><h2>${state.mode==='scout'?'Opponents':'Seasons'}</h2><button data-action="create" title="${state.mode==='scout'?'Add opponent':'New season'}" aria-label="${state.mode==='scout'?'Add opponent':'New season'}">+</button></div><div class="rail-links">${railLink('library',state.mode==='scout'?'All opponents':'Season library','folder',state.page==='library')}${rows||railLink('create','Get started','upload')}</div></div><div class="rail-divider"><div class="rail-subtitle">${season?esc(season.kind==='scout'?season.opponent:seasonTitle(season)):'Program tools'}</div><div class="rail-links">${season&&state.mode==='program'?railLink('roster','Roster','notes',false,`${season.roster||0} players`):''}${railLink('film','Film & storage','film')}${season&&state.mode==='program'?railLink('guide','Season setup','tag'):''}${railLink('manage','Manage program','pencil')}</div></div><div class="rail-foot">${icon('folder')} Local library<strong>${esc(currentProgram()?.name||'Your coaching workspace')}</strong></div>`;
}
function renderMain(){
  if(state.page==='first'){renderFirst();return;}
  if(state.page==='library'||!currentSeason()){renderLibrary();return;}
  const season=currentSeason(),plays=season.games.reduce((sum,game)=>sum+game.plays,0),charted=season.games.reduce((sum,game)=>sum+game.charted,0);
  const heading=season.kind==='scout'?season.opponent:seasonTitle(season);
  $('#main').innerHTML=`<header class="page-head"><div><button class="back-library" data-action="library">${icon('folder')}${state.mode==='scout'?'Opponent library':'Season library'}</button><h1>${esc(heading)}</h1><p class="muted"><span>${season.kind==='scout'?`${season.year} &middot; ${esc(season.level)} &middot; Opponent scout`:esc(currentProgram().name)}</span><span>${season.games.length} games</span>${season.kind==='program'?`<span>${esc(season.record||'0-0')} record</span>`:''}<span>${charted} / ${plays} plays charted</span></p></div><div class="page-actions">${command('season-report',state.mode==='scout'?'Scout report':'Season report','quiet season-report','stats')}${command('add-game',state.mode==='scout'?'Add source game':'Add game','primary','upload')}</div></header><div class="game-workspace"><section class="library-pane" aria-label="Games"><div class="library-tools"><label class="search"><input id="game-search" aria-label="Search games" placeholder="${state.mode==='scout'?'Search source games...':'Search games...'}" value="${esc(state.query)}"></label><select class="sort" id="game-sort" aria-label="Sort games"><option value="newest">Newest first</option><option value="schedule">Schedule order</option></select><div class="view-switch" role="group" aria-label="Game view"><button data-view="grid" aria-label="Grid view" title="Grid view" aria-pressed="${state.view==='grid'}">&#9638;</button><button data-view="list" aria-label="List view" title="List view" aria-pressed="${state.view==='list'}">&#9776;</button></div></div><div class="filters" role="group" aria-label="Filter games">${[['all','All games',season.games.length],['chart','To chart',season.games.filter(g=>g.charted<g.plays||!g.plays).length],['film','Film needed',season.games.filter(g=>!g.film).length]].map(([value,label,count])=>`<button data-filter="${value}" class="${state.filter===value?'active':''}" aria-pressed="${state.filter===value}">${label}<span>${count}</span></button>`).join('')}</div><div id="game-grid" class="game-grid ${state.view==='list'?'list':''}"></div><div class="section-foot"><span id="game-count"></span><div class="roster-action">${state.mode==='program'?`<span>${season.roster||0} players</span>`:''}<button data-action="${state.mode==='scout'?'season-report':'roster'}">${state.mode==='scout'?'Open opponent report':'View roster'} &rarr;</button></div></div></section><aside class="detail-pane" id="game-detail" aria-label="Selected game"></aside></div>`;
  $('#game-sort').value=state.sort;renderGames();renderDetail();
}
function thumbnail(game,detail=false){return `<div class="thumbnail">${game.film&&game.photo?`<img src="assets/${game.photo}.jpg" alt="Game film: ${esc(game.opponent)}" loading="eager">`:`<span class="film-missing">${icon('film')}${game.film?'Film linked':'No film linked'}</span>`}${game.week?`<span class="week">Week ${game.week}</span>`:''}${game.film&&game.duration?`<span class="duration">${esc(game.duration)}</span>`:''}${detail&&game.film?`<button data-action="watch" aria-label="Watch ${esc(gameTitle(game))}" title="Watch game film">${icon('play')}</button>`:''}</div>`;}
function filteredGames(){return (currentSeason()?.games||[]).filter(game=>(state.filter!=='chart'||game.charted<game.plays||!game.plays)&&(state.filter!=='film'||!game.film)&&`${gameTitle(game)} ${fullGameTitle(game)} ${game.week?`Week ${game.week}`:''}`.toLowerCase().includes(state.query.trim().toLowerCase())).sort((a,b)=>{if(!a.date)return b.date?1:a.id.localeCompare(b.id);if(!b.date)return -1;return (state.sort==='newest'?b.date.localeCompare(a.date):a.date.localeCompare(b.date))||(Number(a.week||0)-Number(b.week||0))||a.id.localeCompare(b.id);});}
function renderGames(){
  const games=filteredGames();$('#game-grid').className=`game-grid ${state.view==='list'?'list':''}`;
  $('#game-grid').innerHTML=games.length?games.map(game=>`<button class="game-card ${state.gameId===game.id?'selected':''}" data-game="${esc(game.id)}" aria-pressed="${state.gameId===game.id}" aria-label="Select ${esc(gameTitle(game))}">${thumbnail(game)}<div class="game-card-copy"><h3>${esc(gameTitle(game))}</h3><p class="matchup-schools">${esc(state.mode==='scout'?fullGameTitle(game):game.opponentSchool||game.opponent)}</p><div class="game-meta"><span>${esc(shortDate(game.date))}</span><span class="score">${game.score?`${game.score[0]} &ndash; ${game.score[1]} &middot; Final` :game.plays?'Score not set':'Scheduled'}</span></div><div class="card-status"><span>${game.charted} / ${game.plays} charted</span><span class="health ${game.film?'':'warning'}">${game.film?'Film linked':'Link film'}</span></div>${game.charted<game.plays?`<div class="tiny-progress"><span style="width:${100*game.charted/game.plays}%"></span></div>`:''}</div></button>`).join(''):`<div class="empty-results"><h3>${state.query?'No matching games':state.filter==='film'?'All game film is linked':state.filter==='chart'?'All plays are charted':'No games yet'}</h3><p>${state.query?'Try another opponent or week.':state.filter==='chart'?'Ready for Study and Reports.':state.filter==='film'?'No film links need attention.':'Add the opponent and date. Film can be linked now or later.'}</p>${command(state.filter==='all'&&!state.query?'add-game':'clear-filters',state.filter==='all'&&!state.query?'Add game':'Show all games')}</div>`;
  $('#game-count').textContent=`${games.length} of ${currentSeason().games.length} games`;
}
function renderDetail(){
  const game=currentGame(),season=currentSeason();
  if(!game){$('#game-detail').innerHTML=`<h3>Select a game</h3><p class="muted">${season.games.length?'Choose a game to open its film and analysis.':'Your game details will appear here.'}</p>`;return;}
  const pct=game.plays?Math.round(100*game.charted/game.plays):0;
  const teams=matchupNames(game);
  $('#game-detail').innerHTML=`<div class="detail-top"><span>Selected game${game.week?` &middot; Week ${game.week}`:''}</span><button class="icon-btn" data-action="game-menu" title="Game settings and actions" aria-label="Game settings and actions">&hellip;</button></div><div class="detail-main"><div class="detail-identity">${thumbnail(game,true)}<div><h2>${esc(gameTitle(game))}</h2><p class="matchup-schools">${esc(state.mode==='scout'?fullGameTitle(game):game.opponentSchool||game.opponent)}</p><p class="detail-date">${esc(shortDate(game.date))}${game.date?`, ${game.date.slice(0,4)}`:''} &middot; ${esc(season.level)}</p></div></div><div class="scoreboard"><div class="team"><small>${esc(teams[0])}</small><strong>${game.score?game.score[0]:'&ndash;'}</strong></div><span>${game.score?'FINAL':game.plays?'NO SCORE':'SCHEDULED'}</span><div class="team"><small>${esc(teams[1])}</small><strong>${game.score?game.score[1]:'&ndash;'}</strong></div></div></div><div class="detail-side"><div class="detail-status"><span class="health ${game.film?'':'warning'}">${game.film?`${game.clips} clips linked`:'Film not linked'}</span><button data-action="link-film">${game.film?'Manage film':'Link film'}</button></div><div class="progress-title"><span>Charting</span><strong>${game.charted} / ${game.plays}</strong></div><div class="progress-track"><span style="width:${pct}%"></span></div><div class="phase-counts">${(game.phase||[0,0,0]).map((count,index)=>`<span>${['Offense','Defense','ST'][index]} ${count}</span>`).join('')}</div><div class="detail-actions">${command(!game.film?'link-film':'breakdown',!game.film?'Link game film':game.charted<game.plays?'Continue charting':'Open Break Down','primary',!game.film?'folder':'play')}${command('study','Study','','film',game.plays?'':'disabled')}${command('reports','Reports','','stats',game.plays?'':'disabled')}${command('plan','<strong>Season plans</strong><span>Open &rarr;</span>','plan-link')}</div>${game.lastPlay?`<div class="resume-note">${icon('play')} Resume at play ${game.lastPlay}</div>`:''}</div>`;
}
function renderLibrary(){
  const seasons=sortedSeasons();
  $('#main').innerHTML=`<header class="page-head"><div><h1>${state.mode==='scout'?'Opponent library':'Season library'}</h1><p class="muted"><span>${esc(currentProgram()?.name||'Your program')}</span><span>${seasons.length} ${state.mode==='scout'?'opponents':'seasons'}</span></p></div><div class="page-actions">${command('create',state.mode==='scout'?'Add opponent':'New season','primary','folder')}</div></header><div class="season-list">${seasons.map(season=>`<button class="season-card" data-action="season" data-id="${season.id}"><div class="season-card-head"><span class="level">${esc(season.level==='Varsity'?'V':season.level)}</span><div><h2>${esc(season.kind==='scout'?season.opponent:seasonTitle(season))}</h2><small>${season.kind==='scout'?`${season.year} &middot; ${esc(season.level)}`:esc(currentProgram().name)}</small></div></div><div class="meta"><span>${season.games.length} games</span><span>${season.games.reduce((n,g)=>n+g.plays,0)} plays</span>${season.kind==='program'?`<span>${season.roster||0} players</span>`:''}</div><div class="open-row"><span>Open ${season.kind==='scout'?'opponent':'season'} &rarr;</span><small>${season.games.filter(g=>g.film).length} / ${season.games.length} games linked</small></div></button>`).join('')||`<div class="empty-results"><h2>${state.mode==='scout'?'No opponents yet':'No seasons yet'}</h2><p>${state.mode==='scout'?'Keep opponent film separate from your own schedule.':'Start with the year and level. Add games and film when ready.'}</p>${command('create',state.mode==='scout'?'Add opponent':'Create season','primary')}</div>`}</div><div class="library-help"><div><h3>${state.mode==='scout'?'Opponent film stays separate':'One program. Separate seasons.'}</h3><p>${state.mode==='scout'?'Each source game keeps both team names and its own film.':'JV and Varsity each keep their own roster, schedule, and reports.'}</p></div>${command('recover','Recover seasons','quiet','undo')}</div>`;
}
function createFields(first=false,scout=false){
  const hasData=state.seasons.length>0;
  return `${first?identityFields('programName','Program'):''}<div class="form-grid"><label class="form-field">Year<input name="year" type="number" min="1900" max="2199" value="2026" required></label><label class="form-field">Level<select name="level" required><option value="JV">JV</option><option value="Varsity">Varsity</option><option value="Freshman">Freshman</option><option value="Other">Other...</option></select></label><label class="form-field full" id="custom-level" hidden>Level name<input name="customLevel" placeholder="e.g. 8th grade"></label>${scout?`${identityFields('opponent','Opponent being scouted')}${identityFields('teamA','Source game: Team A')}${identityFields('teamB','Source game: Team B')}<label class="form-field">Game date<input name="date" type="date"></label>`:''}</div>${!scout?`<div class="name-preview"><small>Season name</small><strong id="generated-name">2026 &middot; JV</strong></div><div class="setup-options"><label><input type="radio" name="setup" value="guided" ${!hasData?'checked':''}><span>Use guided setup<small>${!hasData?'Selected for your first season':'Optional'} &middot; skip any time</small></span></label><label><input type="radio" name="setup" value="manual" ${hasData?'checked':''}><span>${hasData?'Quick create':'Set up manually'}<small>${hasData?'Selected for returning coaches':'Go straight to your season'}</small></span></label></div>`:''}<p class="form-error" role="alert"></p>`;
}
function renderFirst(){
  const scout=state.firstMode==='scout';
  $('#main').innerHTML=`<section class="first-run"><h1>Your football workspace</h1><p>Start with your program, or prepare for an opponent.</p><div class="welcome-options"><button class="welcome-option ${!scout?'active':''}" data-first-mode="program" aria-pressed="${!scout}">${icon('folder')}<span><h2>Our Program</h2><p>Your seasons, roster, games, and film.</p></span></button><button class="welcome-option ${scout?'active':''}" data-first-mode="scout" aria-pressed="${scout}">${icon('scan')}<span><h2>Opponent Scout</h2><p>Opponent film, source games, and scouting reports.</p></span></button></div><form class="first-run-form" id="create-form" data-first="true" data-scout="${scout}"><h2>${scout?'Create your first opponent scout':'Create your first season'}</h2>${createFields(true,scout)}<div class="form-footer"><button class="primary command" type="submit">${scout?'Create opponent scout':'Create season'} ${icon('arrow')}</button></div></form><div class="first-run-bottom">${command('recover','Recover existing seasons','','undo')}${command('sample','Explore a sample season','','play')}</div></section>`;
}
let returnFocus=null;
function openDialog(title,html){returnFocus=document.activeElement;$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;if(!$('#dialog').open)$('#dialog').showModal();}
function closeDialog(){$('#dialog').close();if(returnFocus?.isConnected)returnFocus.focus();}
function destination(route,scope='game'){
  const season=currentSeason(),game=currentGame();
  if(!season){announce('Open a season or opponent first.');state.page='library';render();return;}
  if(scope==='game'&&!game){announce('Select a game first.');return;}
  const names={breakdown:'Break Down',watch:'Film Room',study:'Study',reports:'Reports',plan:'Game plan'};
  openDialog(names[route]||route,`<div class="destination"><small>${esc(currentProgram().name)} / ${esc(seasonTitle(season))}</small><h3>${scope==='season'?esc(state.mode==='scout'?season.opponent:route==='plan'?'Season plans':'Season report'):esc(fullGameTitle(game))}</h3><p>${scope==='season'?`${season.games.length} games &middot; season scope`:game.week?`Week ${game.week} &middot; ${esc(shortDate(game.date))}`:esc(shortDate(game.date))}</p>${route==='breakdown'&&game?.lastPlay?`<p>Continue at play ${game.lastPlay}</p>`:''}</div><p class="preview-disclosure">Design preview: this action opens ${esc(names[route]||route)} with the context shown above. No live app data is changed.</p><div class="form-footer">${command('close','Back to Home')}</div>`);
}
function openGuide(){
  const season=currentSeason();if(!season||state.mode==='scout')return;
  openDialog('Season setup',`<p class="dialog-copy">${esc(currentProgram().name)} &middot; ${esc(seasonTitle(season))}</p><div class="guide-list">${[['Season details',seasonTitle(season),'details',true],['Roster',`${season.roster||0} players`,'roster',!!season.roster],['Film storage','Choose or review your film folder','film',false],['First game',season.games.length?`${season.games.length} games added`:'Opponent, date, and film','add-game',!!season.games.length]].map(([label,detail,action,done],index)=>`<div class="guide-step"><span class="step-number">${done?'&#10003;':index+1}</span><div><strong>${label}</strong><p>${esc(detail)}</p></div><div class="step-actions">${command(action,done?'Review':'Open','quiet')}${command('skip-step','Skip','quiet')}</div></div>`).join('')}</div><div class="form-footer">${command('close','Skip guide')}${command('close','Go to season','primary')}</div>`);
}
function openCreate(){if(!state.programId){state.page='first';render();return;}const scout=state.mode==='scout';openDialog(scout?'Add opponent':'New season',`<p class="dialog-copy">${esc(currentProgram().name)}</p><form id="create-form" data-scout="${scout}">${createFields(false,scout)}<div class="form-footer">${command('close','Cancel')}<button class="primary" type="submit">${scout?'Create opponent scout':'Create season'}</button></div></form>`);}
function openGameForm(edit=false){const game=edit?currentGame():null;const scout=state.mode==='scout';if(!currentSeason()){openCreate();return;}openDialog(edit?'Game settings':scout?'Add source game':'Add game',`<p class="dialog-copy">${esc(currentProgram().name)} &middot; ${esc(seasonTitle(currentSeason()))}</p><form id="game-form" data-edit="${edit}"><div class="form-grid">${scout?`${identityFields('teamA','Team A',game?.teamASchool||game?.teamA||currentSeason().opponentSchool||currentSeason().opponent,game?.teamANickname||'')}${identityFields('teamB','Team B',game?.teamBSchool||game?.teamB||'',game?.teamBNickname||'')}`:`${identityFields('opponent','Opponent',game?.opponentSchool||game?.opponent||'',game?.opponentNickname||'')}`}<label class="form-field">Date<input name="date" type="date" value="${esc(game?.date||'')}"></label>${!scout?`<label class="form-field">Week <small>Optional</small><input name="week" type="number" min="1" max="99" value="${game?.week||''}"></label>`:''}</div><p class="form-error" role="alert"></p><div class="form-footer">${command('close','Cancel')}<button type="submit" class="primary">${edit?'Save details':'Add game'}</button></div></form>`);}
function openFilm(){openDialog('Film & storage',`<p class="dialog-copy">${esc(currentProgram()?.name||'Program film')} ${currentSeason()?`&middot; ${esc(seasonTitle(currentSeason()))}`:''}</p><div class="utility-menu">${command('link-film',`<span>Link film to selected game<small>${esc(currentGame()?gameTitle(currentGame()):'Select a game first')}</small></span>`,'','film',currentGame()?'':'disabled')}${command('storage-settings','<span>Film library root<small>D:\\Football\\Film &middot; shared across seasons</small></span>','','folder')}</div><p class="preview-disclosure">A game folder links to that game. It does not replace the film library root.</p>`);}
function openLinkFilm(){if(!currentGame()){announce('Select a game first.');return;}openDialog('Game film',`<p class="dialog-copy">${esc(gameTitle(currentGame()))}</p><form id="film-form"><label class="form-field">Choose a video<input type="file" name="film" accept="video/*" required></label><p class="preview-disclosure">Preview only. The selected filename is shown locally; no file is uploaded or copied. Production also supports linking a game folder.</p><div class="form-footer">${command('close','Cancel')}<button type="submit" class="primary">Link to this game</button></div></form>`);}
function openRoster(){const season=currentSeason();if(!season||state.mode==='scout'){announce('Open an Our Program season for its roster.');return;}openDialog(`${season.level} roster`, `<p class="dialog-copy">${esc(currentProgram().name)} &middot; ${season.year} &middot; ${season.roster||0} players</p><table class="info-table"><thead><tr><th>Number</th><th>Player</th><th>Position</th></tr></thead><tbody><tr><td>7</td><td>Sample quarterback</td><td>QB</td></tr><tr><td>22</td><td>Sample running back</td><td>RB</td></tr><tr><td>54</td><td>Sample linebacker</td><td>LB</td></tr></tbody></table><p class="preview-disclosure">Roster destination preview. This roster belongs only to ${esc(seasonTitle(season))}; it is not shared with another season or opponent scout.</p><div class="form-footer">${command('close','Back to Home')}</div>`);}
function showUtility(title,detail){openDialog(title,`<p class="dialog-copy">${esc(detail)}</p><p class="preview-disclosure">Destination preview. The existing ${esc(title.toLowerCase())} workflow opens here in production; this comp does not change app settings or files.</p><div class="form-footer">${command('close','Back to Home')}</div>`);}
document.addEventListener('click',event=>{
  const button=event.target.closest('button');if(!button||button.disabled)return;
  if(button.dataset.route){if(button.dataset.route==='home'){state.page=state.seasonId?'season':state.seasons.length?'library':'first';render();}else destination(button.dataset.route,button.dataset.route==='plan'?'season':'game');return;}
  if(button.dataset.mode){state.mode=button.dataset.mode;state.seasonId=null;state.gameId=null;state.query='';state.filter='all';state.page=state.programs.length?'library':'first';state.firstMode=state.mode;render();return;}
  if(button.dataset.firstMode){state.firstMode=button.dataset.firstMode;state.mode=state.firstMode;render();return;}
  if(button.dataset.game){state.gameId=button.dataset.game;renderGames();renderDetail();if(innerWidth<=1050)$('#game-detail').scrollIntoView({block:'start',behavior:'instant'});return;}
  if(button.dataset.view){state.view=button.dataset.view;renderMain();return;}
  if(button.dataset.filter){state.filter=button.dataset.filter;renderMain();return;}
  const action=button.dataset.action;if(!action)return;
  if(action==='close'){closeDialog();return;}
  if(action==='library'){state.page='library';state.seasonId=null;state.gameId=null;render();return;}
  if(action==='season'){if($('#dialog').open)closeDialog();state.seasonId=button.dataset.id;state.page='season';state.query='';state.filter='all';state.gameId=currentSeason()?.games.at(-1)?.id||null;render();return;}
  if(action==='create'){openCreate();return;}
  if(action==='clear-filters'){state.query='';state.filter='all';renderMain();return;}
  if(action==='plan'){destination('plan','season');return;}
  if(['breakdown','watch','study','reports'].includes(action)){destination(action);return;}
  if(action==='season-report'){destination('reports','season');return;}
  if(action==='guide'){openGuide();return;}
  if(action==='skip-step'){button.closest('.guide-step').querySelector('.step-number').textContent='\u2013';button.textContent='Skipped';button.disabled=true;return;}
  if(action==='add-game'){openGameForm();return;}
  if(action==='game-menu'){openDialog('Game actions',`<p class="dialog-copy">${esc(gameTitle(currentGame()))}</p><div class="utility-menu">${command('edit-game','Game settings','','pencil')}${command('link-film','Link or repair film','','film')}${command('game-export','Export game data','','download')}</div>`);return;}
  if(action==='edit-game'){openGameForm(true);return;}
  if(action==='roster'){openRoster();return;}
  if(action==='film'){openFilm();return;}
  if(action==='link-film'){openLinkFilm();return;}
  if(action==='sample'){if($('#dialog').open)closeDialog();setPreview('season');return;}
  if(action==='manage'||action==='settings'){openDialog(action==='manage'?'Manage program':'Settings',`<div class="utility-menu">${command('details','<span>Program & season details<small>Name, year, and level</small></span>','','pencil')}${command('film','Film & storage','','folder')}${command('recover','Backups & recovery','','undo')}${command('add-program','Add another program','','folder')}</div>`);return;}
  if(action==='help'){openDialog('Help & recovery',`<div class="utility-menu">${command('guide','Season setup','','tag',!currentSeason()||state.mode==='scout'?'disabled':'')}${command('recover','Recover seasons','','undo')}${command('sample','Explore sample season','','play')}</div>`);return;}
  if(action==='add-program'){openDialog('Add program',`<form id="program-form">${identityFields('name','Program')}<p class="form-error" role="alert"></p><div class="form-footer">${command('close','Cancel')}<button class="primary" type="submit">Add program</button></div></form>`);return;}
  const utilities={recover:['Backups & recovery','Scan recovery snapshots, preview the seasons found, then choose what to recover. Nothing imports automatically.'],details:['Program & season details',`${currentProgram()?.name||'No program'}${currentSeason()?` / ${seasonTitle(currentSeason())}`:''}`],'storage-settings':['Film library root','D:\\Football\\Film. Changing the root is a separate, confirmed operation.'],'game-export':['Export game data',currentGame()?gameTitle(currentGame()):'Select a game']};
  if(utilities[action])showUtility(...utilities[action]);
});
document.addEventListener('input',event=>{
  if(event.target.id==='game-search'){state.query=event.target.value;renderGames();return;}
  if(event.target.closest('#create-form'))updateGeneratedName(event.target.closest('form'));
});
function updateGeneratedName(form){const year=form.elements.year.value,level=form.elements.level.value;const custom=form.querySelector('#custom-level');custom.hidden=level!=='Other';form.elements.customLevel.required=level==='Other';const name=form.querySelector('#generated-name');if(name)name.textContent=`${year||'Year'} \u00b7 ${level==='Other'?(form.elements.customLevel.value||'Level'):level}`;}
document.addEventListener('change',event=>{
  if(event.target.id==='preview-state'){setPreview(event.target.value);return;}
  if(event.target.id==='game-sort'){state.sort=event.target.value;renderGames();return;}
  if(event.target.id==='program'){if(event.target.value==='new'){if(!state.programs.length){state.page='first';render();return;}openDialog('Add program',`<form id="program-form">${identityFields('name','Program')}<p class="form-error" role="alert"></p><div class="form-footer">${command('close','Cancel')}<button class="primary" type="submit">Add program</button></div></form>`);return;}state.programId=event.target.value;state.seasonId=null;state.gameId=null;state.page='library';render();}
  if(event.target.closest('#create-form'))updateGeneratedName(event.target.closest('form'));
});
document.addEventListener('submit',event=>{
  event.preventDefault();const form=event.target,values=Object.fromEntries(new FormData(form));
  if(form.id==='create-form'){
    const first=form.dataset.first==='true',scout=form.dataset.scout==='true';
    const level=(values.level==='Other'?values.customLevel:values.level).trim();const year=String(values.year).trim();
    if(!level||!/^\d{4}$/.test(year)){form.querySelector('.form-error').textContent='Enter a four-digit year and a level.';return;}
    if(scout&&(!values.opponent.trim()||!values.teamA.trim()||!values.teamB.trim()||values.teamA.trim().toLowerCase()===values.teamB.trim().toLowerCase())){form.querySelector('.form-error').textContent='Name the opponent and enter two different source-game teams.';return;}
    if(first){const school=values.programName.trim(),nickname=(values.programNameNickname||'').trim(),name=fullIdentity(school,nickname);if(!school){form.querySelector('.form-error').textContent='Enter a school or organization name.';return;}state.programId='program-'+Date.now();state.programs.push({id:state.programId,name,school,nickname});}
    const duplicate=state.seasons.find(s=>s.programId===state.programId&&s.year===year&&s.level.toLowerCase()===level.toLowerCase()&&s.kind===(scout?'scout':'program')&&(!scout||(s.opponentSchool||s.opponent).toLowerCase()===values.opponent.trim().toLowerCase()));
    if(duplicate){form.querySelector('.form-error').innerHTML=`${esc(seasonTitle(duplicate))} already exists. ${command('season','Open existing season','quiet','',`data-id="${duplicate.id}"`)}`;return;}
    const id='season-'+Date.now(),season={id,programId:state.programId,year,level,kind:scout?'scout':'program',roster:0,record:'0-0',games:[]};
    if(scout){season.opponentSchool=values.opponent.trim();season.opponentNickname=(values.opponentNickname||'').trim();season.opponent=fullIdentity(season.opponentSchool,season.opponentNickname);season.games.push({id:'game-'+Date.now(),opponent:season.opponent,teamASchool:values.teamA.trim(),teamANickname:(values.teamANickname||'').trim(),teamA:fullIdentity(values.teamA,values.teamANickname||''),teamBSchool:values.teamB.trim(),teamBNickname:(values.teamBNickname||'').trim(),teamB:fullIdentity(values.teamB,values.teamBNickname||''),date:values.date,plays:0,charted:0,clips:0,film:false,score:null,phase:[0,0,0]});}
    state.seasons.push(season);Object.assign(state,{mode:season.kind,page:'season',seasonId:id,gameId:season.games[0]?.id||null,query:'',filter:'all'});closeDialog();render();
    if(!scout&&values.setup==='guided')openGuide();else announce(`${scout?'Opponent scout':'Season'} created in preview.`);return;
  }
  if(form.id==='game-form'){
    const season=currentSeason(),scout=state.mode==='scout';const edit=form.dataset.edit==='true';const game=edit?currentGame():{id:'game-'+Date.now(),plays:0,charted:0,clips:0,film:false,score:null,phase:[0,0,0]};
    if(scout){game.teamASchool=values.teamA.trim();game.teamANickname=(values.teamANickname||'').trim();game.teamA=fullIdentity(game.teamASchool,game.teamANickname);game.teamBSchool=values.teamB.trim();game.teamBNickname=(values.teamBNickname||'').trim();game.teamB=fullIdentity(game.teamBSchool,game.teamBNickname);game.opponent=season.opponent;if(!game.teamA||!game.teamB||game.teamA.toLowerCase()===game.teamB.toLowerCase()){form.querySelector('.form-error').textContent='Enter two different source-game teams.';return;}}else{game.opponentSchool=values.opponent.trim();game.opponentNickname=(values.opponentNickname||'').trim();game.opponent=fullIdentity(game.opponentSchool,game.opponentNickname);if(!game.opponentSchool){form.querySelector('.form-error').textContent='Enter the opponent school or organization.';return;}game.week=values.week?Number(values.week):null;}
    game.date=values.date;if(!edit)season.games.push(game);state.gameId=game.id;state.query='';state.filter='all';closeDialog();render();announce(edit?'Game details updated in preview.':'Game added. Link film whenever ready.');return;
  }
  if(form.id==='film-form'){const file=form.elements.film.files[0];if(!file)return;Object.assign(currentGame(),{film:true,clips:1,duration:null,filename:file.name});closeDialog();renderMain();announce(`${file.name} selected in preview.`);return;}
  if(form.id==='program-form'){const school=values.name.trim(),nickname=(values.nameNickname||'').trim(),name=fullIdentity(school,nickname);if(!school)return;if(state.programs.some(p=>(p.school||p.name).toLowerCase()===school.toLowerCase())){form.querySelector('.form-error').textContent='That program already exists.';return;}const id='program-'+Date.now();state.programs.push({id,name,school,nickname});Object.assign(state,{programId:id,seasonId:null,gameId:null,page:'library'});closeDialog();render();}
});
$('#dialog').addEventListener('click',event=>{if(event.target!==$('#dialog'))return;const r=$('#dialog').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeDialog();});
window.homePreview={state,setPreview,render,filteredGames};
$('#dialog').addEventListener('close',()=>{$('#program').value=state.programId||'new';});
setPreview(initial);
