import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import puppeteer from 'puppeteer';

const base=process.env.HOME_COMP_URL||'http://127.0.0.1:4175/design-comps/home-workspace-2026-08-31/home.html';
const out=path.resolve('design-comps/home-workspace-2026-08-31/captures');
const browser=await puppeteer.launch({args:['--no-sandbox']});
let checks=0;
try{
  const page=await browser.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
  const settle=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  const reset=async(state='season')=>{await page.evaluate(state=>window.homePreview.setPreview(state),state);await settle();await new Promise(resolve=>setTimeout(resolve,160));};
  await page.goto(base,{waitUntil:'networkidle0'});await page.evaluate(()=>document.fonts.ready);
  const boxes=[];
  for(const [width,height,states] of [[1920,1080,['season','library','first','scout','progress']],[1440,900,['season','library','first','scout']],[1280,720,['season','progress']],[768,900,['season']],[390,844,['season','first']]]){
    await page.setViewport({width,height});
    for(const state of states){await reset(state);await page.evaluate(()=>window.scrollTo(0,0));
      const result=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,missingImages:[...document.images].filter(image=>!image.complete||image.naturalWidth===0).map(image=>image.src),font:getComputedStyle(document.querySelector('h1')).fontFamily,heading:document.querySelector('h1').textContent}));
      assert.equal(result.overflow,false,`${width} ${state}: no page overflow`);assert.deepEqual(result.missingImages,[],`${width}: images loaded`);assert.match(result.font,/IBM Plex/);checks+=3;boxes.push({width,height,state,...result});
      await page.screenshot({path:path.join(out,`${width}-${state}.png`),fullPage:width<1000});
    }
  }
  await page.setViewport({width:1440,height:900});await reset();
  const yearGaps=await page.$$eval('.rail-year',els=>els.map(el=>el.nextElementSibling.getBoundingClientRect().top-el.getBoundingClientRect().bottom));
  assert.equal(yearGaps.length,2);assert.equal(yearGaps[0],yearGaps[1]);checks+=2;
  await page.click('#season-rail [data-id="varsity26"]');await settle();
  assert.match(await page.$eval('#season-rail .rail-divider',el=>el.textContent),/2026.*Varsity/);
  assert.match(await page.$eval('#season-rail [data-action="roster"]',el=>el.textContent),/44 players/);
  await page.click('#season-rail [data-action="roster"]');assert.match(await page.$eval('#dialog-body',el=>el.textContent),/2026/);checks+=3;
  await page.keyboard.press('Escape');await reset();
  await page.click('[data-game="g3"]');await page.click('#game-detail [data-action="reports"]');
  assert.match(await page.$eval('#dialog-body',el=>el.textContent),/OL Refuge Ravens/);checks++;
  await page.click('#dialog [data-action="close"]');await page.click('[data-action="season-report"]');
  assert.match(await page.$eval('#dialog-body',el=>el.textContent),/6 games.*season scope/);checks++;
  await page.keyboard.press('Escape');await page.click('#game-detail [data-action="plan"]');assert.match(await page.$eval('#dialog-body',el=>el.textContent),/Season plans/);assert.match(await page.$eval('#dialog-body',el=>el.textContent),/season scope/);checks+=2;await page.keyboard.press('Escape');await page.type('#game-search','Holy');assert.equal(await page.$$eval('[data-game]',els=>els.length),1);checks++;
  await page.click('[data-filter="film"]');assert.equal(await page.$$eval('[data-game]',els=>els.length),0);checks++;
  await reset();await page.select('#game-sort','schedule');assert.equal(await page.$eval('[data-game]',el=>el.dataset.game),'g1');checks++;
  await page.click('[data-mode="scout"]');assert.match(await page.$eval('h1',el=>el.textContent),/Opponent library/);assert.equal(await page.$$eval('.season-card',els=>els.length),1);checks+=2;
  await page.click('.season-card');await page.click('#game-detail [data-action="reports"]');assert.match(await page.$eval('#dialog-body',el=>el.textContent),/Notre Dame Prep vs\. Divine Child/);checks++;
  await page.keyboard.press('Escape');assert.equal(await page.$$eval('#season-rail [data-action="roster"]',els=>els.length),0);checks++;
  await reset('library');await page.click('.page-actions [data-action="create"]');
  assert.equal(await page.$eval('[name="setup"]:checked',el=>el.value),'manual');checks++;
  await page.click('#create-form [type="submit"]');assert.match(await page.$eval('.form-error',el=>el.textContent),/already exists/);assert.equal(await page.evaluate(()=>homePreview.state.seasons.length),4);checks+=2;
  await page.screenshot({path:path.join(out,'1440-duplicate-season.png')});await page.keyboard.press('Escape');
  await page.click('.page-actions [data-action="create"]');await page.$eval('[name="year"]',el=>{el.value='2027';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.select('[name="level"]','Varsity');
  assert.equal(await page.$eval('#generated-name',el=>el.textContent),'2027 \u00b7 Varsity');checks++;
  await page.screenshot({path:path.join(out,'1440-create-season.png')});
  await page.click('#create-form [type="submit"]');assert.equal(await page.$eval('h1',el=>el.textContent),'2027 \u00b7 Varsity');assert.equal(await page.$eval('#dialog',el=>el.open),false);checks+=2;
  await reset('first');assert.equal(await page.$eval('[name="setup"]:checked',el=>el.value),'guided');checks++;
  await page.type('[name="programName"]','Test Mavericks');await page.click('#create-form [type="submit"]');
  assert.equal(await page.$eval('#dialog-title',el=>el.textContent),'Season setup');checks++;
  await page.click('[data-action="skip-step"]');assert.match(await page.$eval('.guide-list',el=>el.textContent),/Skipped/);checks++;
  await page.screenshot({path:path.join(out,'1440-guided-setup.png')});await page.click('#dialog [data-action="close"]');
  const id=await page.evaluate(()=>homePreview.state.seasonId);await page.click('#season-rail [data-action="guide"]');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>homePreview.state.seasonId),id);checks++;
  await page.click('.page-actions [data-action="add-game"]');await page.type('[name="opponent"]','Test Opponent');await page.click('#game-form [type="submit"]');
  assert.match(await page.$eval('#game-detail',el=>el.textContent),/Test Opponent/);assert.match(await page.$eval('#game-detail',el=>el.textContent),/Film not linked/);checks+=2;
  await reset('first');await page.type('[name="programName"]','Manual Mavericks');await page.click('[name="setup"][value="manual"]');await page.click('#create-form [type="submit"]');assert.equal(await page.$eval('#dialog',el=>el.open),false);checks++;
  await reset('progress');await page.click('[data-view="list"]');await page.screenshot({path:path.join(out,'1440-list-progress.png')});await page.click('[data-game="a2"]');
  assert.equal(await page.$eval('#game-detail .primary',el=>el.textContent.trim()),'Link game film');checks++;
  await page.click('[data-mode="scout"]');await page.click('.page-actions [data-action="create"]');await page.screenshot({path:path.join(out,'1440-create-opponent.png')});await page.keyboard.press('Escape');
  await reset();
  assert.match(await page.$eval('#game-detail h2',el=>el.textContent),/Mavericks vs\. Wildcats/);
  assert.match(await page.$eval('#game-detail .matchup-schools',el=>el.textContent),/Holy Family/);
  assert.match(await page.$eval('.section-foot [data-action="roster"]',el=>el.textContent),/^View roster/);
  assert.equal(await page.$eval('.section-foot .roster-action>span',el=>el.textContent),'32 players');checks+=4;
  const insets=await page.$eval('#game-detail',el=>{const r=el.getBoundingClientRect();return [...el.querySelectorAll('button,.progress-track,.team,.phase-counts')].map(child=>r.right-child.getBoundingClientRect().right);});
  assert.ok(insets.every(value=>value>=15),'Detail content respects right padding');checks++;
  await page.evaluate(()=>{const g=homePreview.state.seasons[0].games.find(g=>g.id==='g6');g.opponentNickname='Mavericks';g.opponent='Holy Family Mavericks';homePreview.render();});
  assert.equal(await page.$eval('#game-detail h2',el=>el.textContent),'St. Joseph Mavericks vs. Holy Family Mavericks');checks++;
  await page.evaluate(()=>{const g=homePreview.state.seasons[0].games.find(g=>g.id==='g6');delete g.opponentNickname;g.opponent='Unparsed Legacy School Wildcats';homePreview.render();});
  assert.match(await page.$eval('#game-detail h2',el=>el.textContent),/Unparsed Legacy School Wildcats/);checks++;
  await reset('progress');assert.equal(await page.$eval('.resume-note use',el=>el.getAttribute('href')),'../../assets/icons.svg#icon-play');checks++;
  await reset('first');await page.type('[name="programName"]','St. Joseph');await page.type('[name="programNameNickname"]','Mavericks');
  await page.screenshot({path:path.join(out,'1440-first-identity.png')});await page.click('[name="setup"][value="manual"]');await page.click('#create-form [type="submit"]');
  const program=await page.evaluate(()=>homePreview.state.programs[0]);assert.equal(program.school,'St. Joseph');assert.equal(program.nickname,'Mavericks');assert.equal(program.name,'St. Joseph Mavericks');checks+=3;
  await page.click('.page-actions [data-action="add-game"]');await page.type('[name="opponent"]','Holy Family');await page.type('[name="opponentNickname"]','Wildcats');
  await page.screenshot({path:path.join(out,'1440-game-identity.png')});await page.click('#game-form [type="submit"]');
  assert.match(await page.$eval('#game-detail h2',el=>el.textContent),/Mavericks vs\. Wildcats/);checks++;
  await page.click('#game-detail [data-action="game-menu"]');await page.click('[data-action="edit-game"]');
  assert.equal(await page.$eval('[name="opponent"]',el=>el.value),'Holy Family');assert.equal(await page.$eval('[name="opponentNickname"]',el=>el.value),'Wildcats');checks+=2;await page.keyboard.press('Escape');
  await reset('season');await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));await page.screenshot({path:path.join(out,'1440-season-bottom.png')});
  await reset('first');await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));await page.screenshot({path:path.join(out,'1440-first-bottom.png')});
  assert.deepEqual(errors,[]);checks++;fs.writeFileSync(path.join(out,'verification.json'),JSON.stringify({checks,errors,viewports:boxes},null,2));
  console.log(`${checks} checks passed. Home routes, structured naming, duplicate protection, sorting, workspace isolation, guided/manual creation, optional guide, asset loading and viewport containment. Screenshots captured; visual inspection is separate.`);
}finally{await browser.close();}
